CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
username VARCHAR(255) NOT NULL,
password VARCHAR(20) NOT NULL,
description VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE items (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
price INT NOT NULL, 
description VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);